apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: api-scp
  name: api-scp
spec:
  replicas: 1
  strategy:
    type: Rolling
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - api-scp
      from:
        kind: ImageStreamTag
        name: api-scp:latest
    type: ImageChange
  template:
    metadata:
      labels:
        io.kompose.service: api-scp
    spec:
      containers:
      - image: ' '
        name: api-scp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}        
      restartPolicy: Always
status: {}